### ISSUE TITLE
Regex is not correct in _process_tasks() function

### ISSUE THREAD

**Issue by mgsotelo** [RockProfile/Ansible-Output-Parser#24]
The library fails at obtaining failures (pun intended). My code is the following.  

```
        with open(f'../logs/ansible_exec_{moment}.log', 'r') as outputlog:
            output = outputlog.read()
            fails = Play(output).failures()
            logger.debug(fails)
```

And the error message I get is the following:

```
Traceback (most recent call last):
  File "/home/mario/whitestack/whitevault/src/main.py", line 82, in main
    fails = Play(output).failures()
  File "/home/mario/whitestack/whitevault/venv/lib/python3.10/site-packages/ansible_parser/play.py", line 19, in __init__
    self._process_play(play_output)
  File "/home/mario/whitestack/whitevault/venv/lib/python3.10/site-packages/ansible_parser/play.py", line 45, in _process_play
    tasks: Tasks = Tasks(item)
  File "/home/mario/whitestack/whitevault/venv/lib/python3.10/site-packages/ansible_parser/tasks.py", line 18, in __init__
    self._process_tasks(tasks_info)
  File "/home/mario/whitestack/whitevault/venv/lib/python3.10/site-packages/ansible_parser/tasks.py", line 38, in _process_tasks
    print(f"WARNING: Failed parsing line '{task_info}'")
ValueError: I/O operation on closed file.
```

This error can be easily fixed updating the regular expression inside _process_tasks() function from this => `([a-z]+):[ ]+\[([^]]+)](?::[ ]+(.+))?` to this => `([a-z]+):[ ]+\[([^\]]+)](?::[ ]+(.+))?`. I'm submitting a pull request. 

You can find the testing I've made here https://regexr.com/73ojf

**Comment by petermcd** [comment]
Thanks for the PR. Merged, a release will follow shortly/
