### ISSUE TITLE
cant parse logs

### ISSUE THREAD

**Issue by shoshirizel** [RockProfile/Ansible-Output-Parser#32]
try with fail, got a lot of errors like:
WARNING: Failed parsing line '    ]'
WARNING: Failed parsing line '}'

try with log file
log_plays = Logs(log_file=log_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/ice/automation/nightly/ice_healthcheck_venv/lib/python3.9/site-packages/ansible_parser/logs.py", line 27, in __init__
    self._process_log(log_file=log_file)
  File "/usr/share/ice/automation/nightly/ice_healthcheck_venv/lib/python3.9/site-packages/ansible_parser/logs.py", line 40, in _process_log
    if line_part[1].startswith('PLAY ['):
IndexError: list index out of range

did you test your code ?

**Comment by petermcd** [comment]
Yes I did test my code.

It is impossible to help you here as you have not provided the log file that you are trying to parse. I suspect it isn't a log file you are trying to parse at all and rather the output of running a playbook.

**Comment by shoshirizel** [comment]
Right, it's the output of the running playbook, sorry maybe I didn't
understand correct what you pkg does

‫בתאריך יום א׳, 22 בספט׳ 2024 ב-22:16 מאת ‪Peter McDonald‬‏ <‪
***@***.***‬‏>:‬

**Comment by petermcd** [comment]
There are  main things the package does, firstly, it can parse the output Ansible puts into a log file. This is done from logs.py.

Secondly, and looks like what you are after, is that it can parse the output that comes from running a playbook, this is done from plays.py.

**Comment by shoshirizel** [comment]
I try both, by log file that I filled with the output and by out as str, I
read your readme..

‫בתאריך יום ב׳, 23 בספט׳ 2024 ב-20:27 מאת ‪Peter McDonald‬‏ <‪
***@***.***‬‏>:‬

**Comment by petermcd** [comment]
Can you provide the playbook output you are trying to parse and I can take a look at it.
